// ===== SwiftLab 教学数据 =====
// 正文里 [[key:显示文字]] 可点击弹出术语解释(小白版)

const GLOSSARY = {
  swift: {
    title: "Swift(语言)",
    body: "苹果发明的编程语言,专门用来写 iPhone / Mac 的 App。就像中文英文一样,它是一种\"和电脑说话\"的语言——只是语法特别严格,写错一个字电脑就听不懂。",
  },
  swiftui: {
    title: "SwiftUI(画界面的框架)",
    body: "苹果提供的一大箱\"现成积木\":文字、按钮、输入框、列表都是拼好的零件,你只管挑零件、搭起来。系统自带的天气、提醒事项 App 就是用它写的。",
  },
  xcode: {
    title: "Xcode(工厂)",
    body: "苹果官方的开发工具,免费。它是编辑器 + 翻译官 + 组装车间的合体:你在里面写代码,按一个键,它把代码翻译成电脑能执行的 App。做 Mac / iPhone App 必须用它。",
  },
  compile: {
    title: "编译",
    body: "把你写的代码\"翻译\"成电脑真正能执行的机器指令,这个过程叫编译。写错字时,编译器会报错并告诉你哪一行有问题——它是你最严格也最有用的老师。",
  },
  view: {
    title: "界面(View)",
    body: "屏幕上你能看到的一切:文字、按钮、列表、颜色。在 SwiftUI 里,每个零件都是一个 View,大 View 由小 View 拼成,像套娃。",
  },
  state: {
    title: "数据 / 状态(State)",
    body: "App 记住的东西:任务列表、完成了没有、连续几天。界面是给人看的\"皮\",数据才是 App 的\"魂\"。",
  },
  atstate: {
    title: "@State(记性贴纸)",
    body: "贴在变量前面的标记,意思是:\"SwiftUI,盯住这个值!它一变,你就重画界面。\"没有这张贴纸,数据变了界面也不会动。",
  },
  variable: {
    title: "变量(var)",
    body: "一个带名字的盒子,里面放着一个值,随时可以换。var newTask = \"\" 的意思是:造一个叫 newTask 的盒子,先放一段空文字进去。",
  },
  letconst: {
    title: "常量(let)",
    body: "也是带名字的盒子,但盖子是焊死的——放进去就不许换。Swift 鼓励能用 let 就用 let,防止值被意外改掉。",
  },
  string: {
    title: "字符串(String)",
    body: "一段文字的正式叫法。写在双引号里:\"跑步 3 公里\" 就是一个字符串。两个引号中间什么都没有(\"\")叫空字符串。",
  },
  array: {
    title: "数组(Array)",
    body: "一排格子,按顺序放东西。[String] 表示\"只装字符串的一排格子\"。数组能 append(往队尾加)、能数个数、能一个个拿出来画到屏幕上。",
  },
  body: {
    title: "body(长相说明书)",
    body: "每个界面零件必须回答的问题:\"你长什么样?\"答案就写在名叫 body 的属性里。SwiftUI 每次重画界面,都是来读这份说明书。",
  },
  struct: {
    title: "struct(结构体)",
    body: "自己发明一种\"复合数据\"的方法。任务不只是一句话,它有标题、有奖励、有完成状态——用 struct 把这三样打包成一个 PlanTask 类型,一个变量就能拎着走。",
  },
  binding: {
    title: "$ 绑定(双向电线)",
    body: "变量前加 $,把\"读\"和\"写\"两根线都接给对方。输入框需要它:既要显示你的变量,又要在你打字时把新内容写回去。",
  },
  foreach: {
    title: "ForEach(每个都画一遍)",
    body: "对数组说:\"里面每一个元素,都照这个模子画一遍。\"数组有 3 个就画 3 行,有 10 个就画 10 行。列表就是这么来的。",
  },
  action: {
    title: "事件(Action)",
    body: "用户的每一次点击、输入、拖动。事件的唯一使命是修改数据——数据变了,界面自动跟上。你从不直接改界面。",
  },
  declarative: {
    title: "声明式",
    body: "只描述\"数据长这样时,界面应该长那样\",而不是命令电脑\"第一步画这个、第二步挪那个\"。SwiftUI 是声明式的:你管描述,它管重画。",
  },
  appbundle: {
    title: ".app(应用包)",
    body: "Mac 上一个 App 的\"成品盒子\":双击图标就能跑。它其实是个文件夹,里面装着编译好的程序、图标和说明书(右键任何 App 选\"显示包内容\"可以偷看)。",
  },
  modifier: {
    title: "修饰符(Modifier)",
    body: "挂在零件后面的\".xxx()\"链条,负责调样式:.font() 改字体、.padding() 加留白、.foregroundStyle() 改颜色。像给积木喷漆。",
  },
  guardkw: {
    title: "guard(门卫)",
    body: "\"不满足条件就别往下走\"。guard !newTask.isEmpty else { return } 的意思:输入框是空的?那这次点击当没发生,直接回去。",
  },
};

// ===== 第一站:什么是 App(六幕)=====
const S1 = [
  {
    title: "从你已经会的开始",
    visual: '<div><div class="v-emoji">✅</div><div class="v-caption">你的 iCanDoIt,已经躺在你的应用程序文件夹里</div></div>',
    body: "<p>你每天都在用 iCanDoIt:打开、写下今天想做的事、完成后打勾、看彩带飞起来。</p><p>这一站我们回答一个问题:<strong>这个 App 到底是个什么东西?</strong>拆开之后你会发现,它比想象中简单得多。</p><p>(放心,这一站一行代码都不用写。)</p>",
  },
  {
    title: "看到的一切,叫界面",
    visual: '<div><div class="v-row"><span class="v-chip">文字</span><span class="v-chip">按钮</span><span class="v-chip">输入框</span><span class="v-chip">列表</span></div><div class="v-caption">屏幕上的每一样东西,都是一个零件</div></div>',
    body: "<p>屏幕上你能看到的一切——标题、打勾的圆圈、任务列表、彩带——统称[[view:界面(View)]]。</p><p>界面只是\"长相\"。它自己不记得任何事:你关掉 App,界面就消失了。</p>",
  },
  {
    title: "记住的一切,叫数据",
    visual: '<div><div class="v-big">📦 [\"跑步\", \"读书\"]<br>✅ 完成:1 / 2</div><div class="v-caption">这些才是 App 真正\"拥有\"的东西</div></div>',
    body: "<p>任务列表、完成了没有、连续打卡几天——这些是[[state:数据(State)]]。</p><p>关掉 App 再打开,任务还在,是因为数据被存到了硬盘上。<strong>界面是皮,数据是魂。</strong></p>",
  },
  {
    title: "你的每次点击,叫事件",
    visual: '<div><div class="v-row"><span class="v-chip">👆 点击</span><span class="v-arrow">→</span><span class="v-chip">📦 数据变了</span><span class="v-arrow">→</span><span class="v-chip">🖥 界面跟着变</span></div><div class="v-caption">注意方向:点击改的是数据,不是界面</div></div>',
    body: "<p>你点\"完成\"的那一刻,发生了三件事:[[action:事件]]触发 → 数据里的 isDone 从 false 变成 true → 界面上出现删除线。</p><p>关键在顺序:<strong>你从来没有直接改界面,你改的永远是数据。</strong>界面只是数据的倒影。</p>",
  },
  {
    title: "SwiftUI 的规矩",
    visual: '<div><div class="v-big">\"数据长这样时,<br>界面就画成那样\"</div><div class="v-caption">你负责描述,它负责重画</div></div>',
    body: "<p>[[swiftui:SwiftUI]] 的工作方式是[[declarative:声明式]]的:你不用一步步指挥电脑\"先画这个再挪那个\",只需要描述规则——比如\"isDone 是 true 的任务,文字加删除线\"。</p><p>之后每当数据变化,SwiftUI 自动按你的描述重画整个界面。<strong>你管描述,它管画。</strong></p>",
  },
  {
    title: "公式揭晓",
    visual: '<div><div class="v-formula">界面 = f(数据)</div><div class="v-caption">整个 iCanDoIt,就是把这个公式写了三遍</div></div>',
    body: "<p>这就是现代 App 开发的全部秘密:<strong>界面是数据的函数。</strong>数据进,界面出。</p><p>你需要的工具只有三样,全部免费:[[swift:Swift]] 是语言,[[swiftui:SwiftUI]] 是积木箱,[[xcode:Xcode]] 是工厂。</p><p>下一站,亲眼看这个 App 怎么从一行字长成完整的样子。</p>",
  },
];

// ===== 第二站:看它长大(九步)=====
// code: 每行 { t: 文本, add: 是否本步新增 }
const S2 = [
  {
    beat: "建个空壳",
    title: "Xcode 送你一个能跑的最小 App",
    xcode: "打开 Xcode → Create New Project → macOS → App → 一路 Next。",
    narration: "新项目一建好,[[xcode:Xcode]] 就送你这几行代码——一个只会显示一行字的 App。别小看它,按 <kbd>⌘R</kbd> 它真的能跑起来。我们整个 App 都将从这几行长出来。",
    code: [
      { t: "import SwiftUI" },
      { t: "" },
      { t: "struct ContentView: View {" },
      { t: "    var body: some View {" },
      { t: "        Text(\"Hello, world!\")" },
      { t: "    }" },
      { t: "}" },
    ],
    mock: "hello",
    mockCaption: "右边就是它跑起来的样子",
  },
  {
    beat: "写下问候",
    title: "把它变成我们的开场白",
    xcode: "直接改 ContentView.swift 里的文字,保存,右侧预览立刻跟着变。",
    narration: "把 Hello world 换成我们的问题,再挂几个[[modifier:修饰符]]:调大字号、染上紫色、声明走深色系。注意读法:Text 是零件,后面的 .font()、.foregroundStyle() 像链条一样一节节挂上去。",
    code: [
      { t: "import SwiftUI" },
      { t: "" },
      { t: "struct ContentView: View {" },
      { t: "    var body: some View {" },
      { t: "        Text(\"今天想完成什么?\")", add: true },
      { t: "            .font(.system(size: 24, weight: .bold, design: .rounded))", add: true },
      { t: "            .foregroundStyle(.purple)", add: true },
      { t: "            .preferredColorScheme(.dark)", add: true },
      { t: "    }" },
      { t: "}" },
    ],
    mock: "title",
    mockCaption: "开始有 iCanDoIt 的味道了",
  },
  {
    beat: "给它记性",
    title: "@State:App 的记性",
    xcode: "在 ContentView 顶部加三个变量;文件底部新建一个 PlanTask 结构体。",
    narration: "界面要变,先得有能变的[[state:数据]]。我们声明三块记性:输入框的文字、奖励的文字、任务列表。前面贴上 [[atstate:@State]] 这张\"记性贴纸\",SwiftUI 就会盯住它们——一变就重画界面。任务本身用 [[struct:struct]] 打包:标题 + 奖励 + 完成没有,三样合成一个 PlanTask。",
    code: [
      { t: "struct ContentView: View {" },
      { t: "    @State private var newTask = \"\"", add: true },
      { t: "    @State private var newReward = \"\"", add: true },
      { t: "    @State private var tasks: [PlanTask] = []", add: true },
      { t: "" },
      { t: "    var body: some View {" },
      { t: "        // …上一步的 Text 不变" },
      { t: "    }" },
      { t: "}" },
      { t: "" },
      { t: "struct PlanTask: Identifiable {", add: true },
      { t: "    let id = UUID()", add: true },
      { t: "    var title: String", add: true },
      { t: "    var reward: String", add: true },
      { t: "    var isDone = false", add: true },
      { t: "}", add: true },
    ],
    mock: "memory",
    mockCaption: "界面没变,但 App 已经有了三块记性",
  },
  {
    beat: "画出输入框",
    title: "TextField + $:双向电线",
    xcode: "把 body 里的内容包进 VStack(竖着排),下面加一行 HStack(横着排)放两个输入框。",
    narration: "输入框零件叫 TextField。注意变量前面的 <b>$</b>——那是[[binding:双向电线]]:输入框既要显示 newTask 的内容,又要在你打字时把新内容写回去,读写两根线都得接上。VStack / HStack 是排版零件:竖着排、横着排。",
    code: [
      { t: "    var body: some View {" },
      { t: "        VStack(alignment: .leading, spacing: 16) {", add: true },
      { t: "            Text(\"今天想完成什么?\")" },
      { t: "                .font(.system(size: 24, weight: .bold, design: .rounded))" },
      { t: "                .foregroundStyle(.purple)" },
      { t: "" },
      { t: "            HStack {", add: true },
      { t: "                TextField(\"写下一件事…\", text: $newTask)", add: true },
      { t: "                TextField(\"奖励(可选)\", text: $newReward)", add: true },
      { t: "            }", add: true },
      { t: "        }", add: true },
      { t: "        .padding(24)", add: true },
      { t: "        .preferredColorScheme(.dark)" },
      { t: "    }" },
    ],
    mock: "inputs",
    mockCaption: "两个输入框已经接上电线",
  },
  {
    beat: "让「添加」真的添加",
    title: "Button:事件改数据",
    xcode: "在 HStack 里、两个输入框后面,加一个 Button。",
    narration: "Button 有两半:引号里是按钮上的字,花括号里是<b>按下去执行的代码</b>。这段代码只做一件事——改数据:先让 [[guardkw:guard]] 门卫拦住空输入,然后把新任务 append 进数组、清空输入框。<b>没有一行代码去碰界面</b>,但界面会自己长出一行新任务——因为 tasks 变了,SwiftUI 重画。这就是第一站的公式在干活。",
    code: [
      { t: "            HStack {" },
      { t: "                TextField(\"写下一件事…\", text: $newTask)" },
      { t: "                TextField(\"奖励(可选)\", text: $newReward)" },
      { t: "                Button(\"添加\") {", add: true },
      { t: "                    guard !newTask.isEmpty else { return }", add: true },
      { t: "                    tasks.append(PlanTask(title: newTask, reward: newReward))", add: true },
      { t: "                    newTask = \"\"", add: true },
      { t: "                    newReward = \"\"", add: true },
      { t: "                }", add: true },
      { t: "            }" },
    ],
    mock: "addbtn",
    mockCaption: "看右边:输入 → 点添加 → 数组多一个 → 界面长一行",
  },
  {
    beat: "用 ForEach 画出列表",
    title: "数组有几个,就画几行",
    xcode: "在 HStack 下面加一段 ForEach。",
    narration: "[[foreach:ForEach]] 对数组说:\"每个元素都照这个模子画一遍。\"$tasks 带着 $ 是因为待会儿打勾要<b>修改</b>任务(写回数据),所以把双向电线一路接进去。现在 tasks 里有几个任务,屏幕上就有几行——增一个画一行,全自动。",
    code: [
      { t: "            ForEach($tasks) { $task in", add: true },
      { t: "                HStack {", add: true },
      { t: "                    Text(task.title)", add: true },
      { t: "                    Spacer()", add: true },
      { t: "                }", add: true },
      { t: "            }", add: true },
    ],
    mock: "list",
    mockCaption: "三个任务,三行,一一对应",
  },
  {
    beat: "让圆圈能打勾",
    title: "toggle:一点就翻面",
    xcode: "在每行任务的 Text 前面加一个圆圈 Button。",
    narration: "圆圈也是个 Button,按下去执行 <b>task.isDone.toggle()</b>——把 true/false 翻个面。图标跟着数据走:isDone 时用 checkmark.circle.fill(实心勾),否则用 circle(空圈);文字的删除线也一样,.strikethrough(task.isDone)。<b>试试右边的圆圈,真的能点!</b>",
    code: [
      { t: "            ForEach($tasks) { $task in" },
      { t: "                HStack {" },
      { t: "                    Button {", add: true },
      { t: "                        task.isDone.toggle()", add: true },
      { t: "                    } label: {", add: true },
      { t: "                        Image(systemName: task.isDone ? \"checkmark.circle.fill\" : \"circle\")", add: true },
      { t: "                    }", add: true },
      { t: "                    .buttonStyle(.plain)", add: true },
      { t: "" },
      { t: "                    Text(task.title)" },
      { t: "                        .strikethrough(task.isDone)", add: true },
      { t: "                    Spacer()" },
      { t: "                }" },
      { t: "            }" },
    ],
    mock: "check",
    mockCaption: "👆 圆圈是活的,点一下试试",
  },
  {
    beat: "完成时给颗糖",
    title: "if:只在该出现时出现",
    xcode: "在 Text 下面加一个 if 判断。",
    narration: "最后一块拼图:完成任务时亮出奖励。if 的意思是\"满足条件才画这一块\"——任务完成了、而且当初写了奖励,就显示 🎁。字符串里的 <b>\\(task.reward)</b> 是把变量的值嵌进文字里。到这里,iCanDoIt 的核心玩法全部长齐了。",
    code: [
      { t: "                    Text(task.title)" },
      { t: "                        .strikethrough(task.isDone)" },
      { t: "                    if task.isDone && !task.reward.isEmpty {", add: true },
      { t: "                        Text(\"🎁 去领奖:\\(task.reward)\")", add: true },
      { t: "                    }", add: true },
      { t: "                    Spacer()" },
    ],
    mock: "reward",
    mockCaption: "打勾第一条任务,糖出现了",
  },
  {
    beat: "装进你的 Mac",
    title: "从代码到 .app",
    xcode: "日常开发按 ⌘R 试跑;想要成品,Product → Archive 导出 .app。",
    narration: "写代码时按 <kbd>⌘R</kbd>,Xcode 现场[[compile:编译]]并跑给你看,改一行再跑一遍。想要一个能装进应用程序文件夹的成品,用 Product → Archive 导出 [[appbundle:.app]]。(你手上的 iCanDoIt 正式版,就是我用等价的命令行方式打包、再拷进 /Applications 的。)",
    code: [],
    mock: "ship",
    mockCaption: "从一行 Hello world,到 Dock 上的图标",
  },
];

// ===== 第三站:亲手写(挖空)=====
// 骨架行里 ⟦n⟧ 是第 n 个空
const S3_LINES = [
  "import SwiftUI",
  "",
  "struct ContentView: View {",
  "    ⟦0⟧ private var newTask = \"\"",
  "    @State private var tasks: [String] = ⟦1⟧",
  "",
  "    var ⟦2⟧: some View {",
  "        VStack(alignment: .leading, spacing: 16) {",
  "            ⟦3⟧(\"今天想完成什么?\")",
  "",
  "            TextField(\"写下一件事…\", text: ⟦4⟧)",
  "",
  "            Button(\"添加\") {",
  "                tasks.⟦5⟧(newTask)",
  "                newTask = ⟦6⟧",
  "            }",
  "",
  "            ⟦7⟧(tasks.indices, id: \\.self) { i in",
  "                Text(tasks[i])",
  "            }",
  "        }",
  "        .padding(24)",
  "    }",
  "}",
];

const S3_BLANKS = [
  {
    filled: "@State",
    lesson: { title: "🎒 新知识 · App 的记性", body: "界面要跟着数据变,前提是 SwiftUI <b>盯着</b>这个数据。给变量贴上一张\"记性贴纸\",它一变,界面立刻重画。这张贴纸叫 <b>@State</b>。" },
    q: "输入框的文字 newTask 需要被 SwiftUI 盯住。第一个空填什么?",
    options: [
      { label: "var", fb: "var 只是声明一个普通变量,SwiftUI 不会盯着它——值变了,界面也无动于衷。而且这行后面已经有 var 了,缺的是前面的贴纸。" },
      { label: "@State", ok: true },
      { label: "let", fb: "let 是常量,放进去就不许改。输入框的内容随时在变,焊死的盒子装不了它。" },
      { label: "@Magic", fb: "Swift 里没有这个咒语 😄 以 @ 开头的东西叫\"属性包装器\",记性贴纸的真名是 @State。" },
    ],
  },
  {
    filled: "[]",
    lesson: { title: "🎒 新知识 · 数组:一排格子", body: "[String] 表示\"只装[[string:字符串]]的一排格子\"([[array:数组]])。App 刚打开时一个任务都没有,所以要给它一个<b>空数组</b>——一排存在、但什么都没放的格子。" },
    q: "任务列表开局是空的。等号后面填什么?",
    options: [
      { label: "nil", fb: "nil 是\"这个值根本不存在\"。我们要的不是\"不存在\",而是\"存在,但空着\"——就像新买的书架:架子在,书还没放。" },
      { label: "\"\"", fb: "这是空字符串——一段没有字的<b>文字</b>。我们要的是空<b>数组</b>,两回事:一个是空白纸条,一个是空格子架。" },
      { label: "[]", ok: true },
      { label: "[0]", fb: "这个数组里躺着一个数字 0,不是空的;而且格子上写着只收 String,塞数字进去编译器会报错。" },
    ],
  },
  {
    filled: "body",
    lesson: { title: "🎒 新知识 · 长相说明书", body: "每个界面零件都必须回答一个问题:\"你长什么样?\"答案写在一个固定名字的属性里,SwiftUI 每次重画都来读它。这个名字是 <b>body</b>。" },
    q: "这份\"长相说明书\"的名字是?",
    options: [
      { label: "main", fb: "main 是整个程序的\"大门\"(从哪里开始跑),不是界面的说明书。" },
      { label: "body", ok: true },
      { label: "screen", fb: "很合理的猜测,但 Swift 只认约定好的名字——SwiftUI 找的是 body,换名字它就找不到了。" },
      { label: "face", fb: "比 body 还形象 😄 可惜 SwiftUI 只认 body 这个名字。" },
    ],
  },
  {
    filled: "Text",
    lesson: { title: "🎒 新知识 · 屏幕上的一切都是零件", body: "想在屏幕上写字,就造一个文字零件;想要按钮就造 Button,输入框就造 TextField。写字的零件叫 <b>Text</b>,用法:Text(\"想说的话\")。" },
    q: "把\"今天想完成什么?\"显示在屏幕上,用哪个零件?",
    options: [
      { label: "print", fb: "print 是往控制台打印日志<b>给程序员看</b>的,用户的屏幕上什么都不会出现。新手最容易混的一对,记住:给用户看用 Text,给自己调试用 print。" },
      { label: "String", fb: "String 是文字这种<b>数据</b>本身;把数据<b>显示出来</b>的零件是 Text。一个是内容,一个是喇叭。" },
      { label: "Text", ok: true },
      { label: "Word", fb: "SwiftUI 的积木箱里没有这个零件。写字的零件叫 Text。" },
    ],
  },
  {
    filled: "$newTask",
    lesson: { title: "🎒 新知识 · $:双向电线", body: "TextField 很特殊:它既要<b>读</b>你的变量(把内容显示出来),又要<b>写回</b>(你打字时更新它)。在变量前加 <b>$</b>,就是把读、写两根线一起接上([[binding:双向绑定]])。" },
    q: "TextField 要和 newTask 双向连接,这里填什么?",
    options: [
      { label: "newTask", fb: "少了 $,只接了\"读\"这一根线。TextField 必须能写回,Xcode 会直接报错:Cannot convert value of type 'String'…——它要的是绑定,不是值。" },
      { label: "$newTask", ok: true },
      { label: "\"newTask\"", fb: "加了引号就变成文字 \"newTask\" 本身了,和你的变量没有任何关系——输入框里会永远显示这八个字母。" },
      { label: "&newTask", fb: "& 是 C 语言\"取地址\"的写法,Swift 里偶尔也用,但 SwiftUI 的双向绑定符号是 $。" },
    ],
  },
  {
    filled: "append",
    lesson: { title: "🎒 新知识 · 队尾加一个", body: "数组自带一批\"动作\":数个数、取出来、往后加…… 往队尾追加一个元素的动作叫 <b>append</b>:tasks.append(x) 就是把 x 放到队伍最后。" },
    q: "把 newTask 加进任务列表,用哪个动作?",
    options: [
      { label: "add", fb: "很多语言用 add,Swift 的数组偏偏不认——它的追加动作叫 append。选错了编译器会说:value of type '[String]' has no member 'add'。" },
      { label: "push", fb: "push 是\"栈\"这种数据结构的行话。Swift 数组的追加就叫 append,朴实无华。" },
      { label: "append", ok: true },
      { label: "insert", fb: "insert 是\"插到<b>指定位置</b>\",还得多给一个位置参数 insert(x, at: 0)。往队尾加,append 最顺手。" },
    ],
  },
  {
    filled: "\"\"",
    lesson: { title: "🎒 新知识 · 清空输入框", body: "添加完任务,输入框应该清空,好写下一条。清空 = 给它一段<b>空字符串</b>:两个引号,中间什么都不放。注意:nil(不存在)和 \"\"(存在但是空的)是两回事。" },
    q: "添加完把 newTask 清空,等号后面填什么?",
    options: [
      { label: "\"\"", ok: true },
      { label: "nil", fb: "newTask 的类型是 String,Swift 不允许它\"不存在\"。清空不是让它消失,是给它一段空文字 \"\"。" },
      { label: "\" \"", fb: "仔细看,引号里藏着一个空格!输入框看起来空了,其实躺着一个看不见的字符——之后判断\"是不是空\"时会被它骗过。差之毫厘的经典 bug。" },
      { label: "delete", fb: "Swift 没有这种写法。清空一个字符串,就是赋值一个空字符串 \"\"。" },
    ],
  },
  {
    filled: "ForEach",
    lesson: { title: "🎒 新知识 · 每个都画一遍", body: "怎么把数组变成屏幕上的一行行?用一个零件对数组说:\"每个元素都照这个模子画一遍。\"数组有 3 个就画 3 行。这个零件叫 <b>ForEach</b>。" },
    q: "把 tasks 里的每一条画成一行文字,用哪个零件?",
    options: [
      { label: "for", fb: "for 是普通代码里的循环,但 body 是\"长相说明书\"不是普通代码——说明书里要用它的界面版兄弟 ForEach。" },
      { label: "ForEach", ok: true },
      { label: "Repeat", fb: "积木箱里没有这个零件。把数组逐个画出来的零件叫 ForEach。" },
      { label: "List", fb: "接近了!List 确实是列表零件,但它是\"带滚动条的容器\";把数组逐个变成行的是 ForEach。两个常常搭配用:List { ForEach… }。" },
    ],
  },
];

// ===== 第四站:装进你的 Mac =====
const S4_STEPS = [
  { n: "0", body: "<b>前提:</b>Mac 上装好 [[xcode:Xcode]](App Store 免费下载,体积大,耐心等)。<b>你的电脑已经装好了 26.6,直接跳到第 1 步。</b>" },
  { n: "1", body: "打开 Xcode,点 <b>Create New Project</b>(或菜单 File → New → Project)。" },
  { n: "2", body: "顶部选 <b>macOS</b> 标签 → 选中 <b>App</b> → <b>Next</b>。" },
  { n: "3", body: "Product Name 填 <b>MyPlanner</b>;确认 Interface 是 <b>SwiftUI</b>、Language 是 <b>Swift</b>;Testing System 选 None 即可 → <b>Next</b> → 保存到\"下载\"文件夹。" },
  { n: "4", body: "左侧文件列表点开 <b>ContentView.swift</b>,全选里面的内容删掉,把下面这份完整代码粘贴进去。" },
  { n: "5", body: "按 <kbd>⌘R</kbd>(或点左上角 ▶)。第一次运行如果弹出签名或权限提示,选自动/允许即可。" },
  { n: "6", body: "🎉 一个真正的 Mac App 在你手里跑起来了——输入任务、打勾、领奖励,每一行代码你都认识。" },
];

const S4_CODE = [
  "import SwiftUI",
  "",
  "struct ContentView: View {",
  "    @State private var newTask = \"\"",
  "    @State private var newReward = \"\"",
  "    @State private var tasks: [PlanTask] = []",
  "",
  "    var body: some View {",
  "        VStack(alignment: .leading, spacing: 16) {",
  "            Text(\"今天想完成什么?\")",
  "                .font(.system(size: 24, weight: .bold, design: .rounded))",
  "                .foregroundStyle(.purple)",
  "",
  "            HStack {",
  "                TextField(\"写下一件事…\", text: $newTask)",
  "                TextField(\"奖励(可选)\", text: $newReward)",
  "                Button(\"添加\") {",
  "                    guard !newTask.isEmpty else { return }",
  "                    tasks.append(PlanTask(title: newTask, reward: newReward))",
  "                    newTask = \"\"",
  "                    newReward = \"\"",
  "                }",
  "            }",
  "",
  "            ForEach($tasks) { $task in",
  "                HStack {",
  "                    Button {",
  "                        task.isDone.toggle()",
  "                    } label: {",
  "                        Image(systemName: task.isDone ? \"checkmark.circle.fill\" : \"circle\")",
  "                    }",
  "                    .buttonStyle(.plain)",
  "",
  "                    Text(task.title)",
  "                        .strikethrough(task.isDone)",
  "",
  "                    if task.isDone && !task.reward.isEmpty {",
  "                        Text(\"🎁 去领奖:\\(task.reward)\")",
  "                    }",
  "                    Spacer()",
  "                }",
  "            }",
  "            Spacer()",
  "        }",
  "        .padding(24)",
  "        .frame(minWidth: 480, minHeight: 380)",
  "        .preferredColorScheme(.dark)",
  "    }",
  "}",
  "",
  "struct PlanTask: Identifiable {",
  "    let id = UUID()",
  "    var title: String",
  "    var reward: String",
  "    var isDone = false",
  "}",
];

const STOPS = [
  { name: "什么是 App", desc: "先懂 · 零代码" },
  { name: "看它长大", desc: "再看 · 九步慢动作" },
  { name: "亲手写", desc: "动手 · 填空闯关" },
  { name: "装进你的 Mac", desc: "实战 · 真的 Xcode" },
];
